// <auto-generated />
using System;
using AppAdminEmployed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppAdminEmployed.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251011230240_Crear_Tabla_Empleado")]
    partial class Crear_Tabla_Empleado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppAdminEmployed.Models.EmpleadoModel", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IDENTIFICACION")
                        .HasColumnType("int");

                    b.Property<string>("PRIMER_APELLIDO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRIMER_NOMBRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEGUNDO_APELLIDO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEGUNDO_NOMBRE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UUID");

                    b.ToTable("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
