// <auto-generated />
using System;
using AppAdminEmployed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppAdminEmployed.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251025032856_ADD_CREATE_UPDATE_EMPLEADO")]
    partial class ADD_CREATE_UPDATE_EMPLEADO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppAdminEmployed.Models.EmpleadoModel", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CREATEDAT")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GUID_SUPERVISOR")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IDENTIFICACION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRIMER_APELLIDO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRIMER_NOMBRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEGUNDO_APELLIDO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEGUNDO_NOMBRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPDATEDAT")
                        .HasColumnType("datetime2");

                    b.HasKey("UUID");

                    b.HasIndex("GUID_SUPERVISOR");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("AppAdminEmployed.Models.EmpleadoModel", b =>
                {
                    b.HasOne("AppAdminEmployed.Models.EmpleadoModel", "Supervisor")
                        .WithMany("Subordinados")
                        .HasForeignKey("GUID_SUPERVISOR");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("AppAdminEmployed.Models.EmpleadoModel", b =>
                {
                    b.Navigation("Subordinados");
                });
#pragma warning restore 612, 618
        }
    }
}
