// <auto-generated />
using MiAppMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppAdminEmployed.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251011204159_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppAdminEmployed.Models.EmpleadoModel", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IDENTIFICACION")
                        .HasColumnType("int");

                    b.Property<string>("PRIMER_APELLIDO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRIMER_NOMBRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEGUNDO_APELLIDO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEGUNDO_NOMBRE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UUID");

                    b.ToTable("DbEmpleado");
                });
#pragma warning restore 612, 618
        }
    }
}
